name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # 添加条件：如果提交信息包含 [skip ci]，则跳过工作流
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    runs-on: ubuntu-latest

    steps:
      # 你现有的步骤...
      - uses: actions/checkout@v2
      # 其他步骤...
